# Turtle with oto
import turtle
turtle.setup(500,500)
turtle.reset()
turtle.width(10)
turtle.circle(50)
turtle.penup()
turtle.goto(115,0)
turtle.pendown()
turtle.pencolor("red")
turtle.width(10)
turtle.circle(50)
turtle.penup()
turtle.goto(-115,0)
turtle.pendown()
turtle.pencolor("blue")
turtle.width(10)
turtle.circle(50)
turtle.penup()
turtle.goto(-65,-50)
turtle.pendown()
turtle.pencolor("yellow")
turtle.width(10)
turtle.circle(50)
turtle.penup()
turtle.goto(65,-50)
turtle.pendown()
turtle.pencolor("green")
turtle.width(10)
turtle.circle(50)



turtle.done()