import turtle as Shawna

# Setup
Shawna.setup(500,500)
Shawna.showturtle()
Shawna.speed(10)
#Shawna.pencolor("red")
#Shawna.width(10)
Shawna.circle(100)
# Turtle move
## Rectangle
Shawna.forward(100)
Shawna.right(90)
Shawna.forward(100)
Shawna.right(90)
Shawna.forward(100)
Shawna.right(90)
Shawna.forward(100)
Shawna.right(90)
# Rectangle with dots and pause
Shawna.reset
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.right(90)
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.right(90)
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.right(90)
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.dot()
Shawna.forward(30)
Shawna.dot()
Shawna.penup()
Shawna.forward(10)
Shawna.pendown()
Shawna.dot()
Shawna.right(90)

# circle with different size of width and color
Shawna.reset()
Shawna.circle(30)
Shawna.pencolor("red")
Shawna.circle(40)
Shawna.pencolor("yellow")
Shawna.circle(50)
Shawna.pencolor("blue")
Shawna.width(5)
Shawna.circle(60)
Shawna.circle("purple")
Shawna.fillcolor("green")
Shawna.begin_fill()
Shawna.circle(70)
Shawna.end_fill()
Shawna.done()

# Turtle with goto is in other file



